/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dwbook.phonebook;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;

public class App extends Application<PhonebookConfiguration> {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    public String getGreeting() {
        return "Hello worldsssssssss";
    }

    public static void main(String[] args) throws Exception {
        System.out.println("--------->" + new App().getGreeting() + "<---------");
        new App().run(args);
    }

    @Override
    public void initialize(Bootstrap<PhonebookConfiguration> b) {}

    @Override
    public void run(PhonebookConfiguration c, Environment e) throws Exception {
        LOGGER.info("==============Method App#run() called===================");
        for (int i=0; i < c.getMessageRepetitions(); i++) {
            LOGGER.info(c.getMessage());
        }
        LOGGER.info("========================================================");
    }
}
