message: This is a message defined in the configuration file config.yaml.
messageRepetitions: 10 # this will throw error if greater than 10 Look At PhonebookConfiguration
database:
    driverClass: com.mysql.jdbc.Driver
    user: phonebookuser
    password: phonebookpassword
    url: jdbc:mysql://localhost/phonebook
