/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dwbook.phonebook;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import com.dwbook.phonebook.resources.*;
import org.skife.jdbi.v2.DBI;
import io.dropwizard.jdbi.DBIFactory;
import com.sun.jersey.api.client.*;
import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.auth.basic.BasicAuthProvider;
import com.sun.jersey.api.client.filter.HTTPBasicAuthFilter;
import io.dropwizard.auth.CachingAuthenticator;
import com.google.common.cache.CacheBuilderSpec;
import io.dropwizard.views.ViewBundle;
import io.dropwizard.auth.basic.BasicCredentials;
import io.dropwizard.views.ViewBundle;

public class App extends Application<PhonebookConfiguration> {
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    public String getGreeting() {
        return "Hello worldsssssssss";
    }

    public static void main(String[] args) throws Exception {
        System.out.println("--------->" + new App().getGreeting() + "<---------");
        new App().run(args);
    }

    @Override
    public void initialize(Bootstrap<PhonebookConfiguration> b) {
        b.addBundle(new ViewBundle());
    }

    @Override
    public void run(PhonebookConfiguration c, Environment e) throws Exception {
        LOGGER.info("==============Method App#run() called===================");
        for (int i=0; i < c.getMessageRepetitions(); i++) {
            LOGGER.info(c.getMessage());
            LOGGER.info(c.getAdditionalMessage());
        }

        // Create a DBI factory and build a JDBI instance
        final DBIFactory factory = new DBIFactory();
        final DBI jdbi = factory.build(e, c.getDataSourceFactory(), "mysql");
        // Add the resource to the environment
        e.jersey().register(new ContactResource(jdbi, e.getValidator()));
        // build the client and add the resource to the environment
        final Client client = new JerseyClientBuilder(e).build("REST Client");
        client.addFilter(new HTTPBasicAuthFilter("john_doe", "secret"));
        e.jersey().register(new ClientResource(client));

        // Authenticator, with caching support (CachingAuthenticator)
        CachingAuthenticator<BasicCredentials, Boolean> authenticator = 
            new CachingAuthenticator<BasicCredentials, Boolean>( e.metrics(),
                new PhonebookAuthenticator(jdbi), 
                CacheBuilderSpec.parse("maximumSize=10000, expireAfterAccess=10m"));
                // Register the authenticator with the environment
        e.jersey().register(new BasicAuthProvider<Boolean>(authenticator, "Web Service Realm"));
        LOGGER.info("========================================================");
    }
}
